### ISSUE TITLE
 cannot commit transaction: Missing transaction ID for this call. (code: 404)

### ISSUE THREAD

**Issue by asveg** [e-XpertSolutions/f5-rest-client#36]
Hello, I always get: "Unable to commit transaction: Missing transaction ID for this call. (Code: 404)" error when I create pools and members, however, in f5 ltm I can see that the data is uploaded, how to solve this problem ?

**Comment by gilliek** [comment]
Hello @asveg,

I just validated with our internal test suite and I did not encounter any issue with the transactions on the LTM part.

Can you provide me with some code snippet so that I can help you troubleshoot your code?

Given the information you provided so far, I think the problem is that you are not creating the objects within the transaction scope, that's why objects are created on the F5 and that's why the commit is not working, as there is no transaction ID. But it is hard to be 100% sure without your code.

You have an example that explains how to use transaction in the library in the documentation: https://pkg.go.dev/github.com/e-XpertSolutions/f5-rest-client/f5#Client.Begin

**Comment by asveg** [comment]
Hello,


I'm glad to get your reply, I have debugged many times, refer to the link in the documentation:&nbsp;&nbsp;https://github.com/e-XpertSolutions/f5-rest-client/blob/master/f5/example_test.go, and found that I have a parameter to write Wrong, the problem has been solved, thank you!







2965836218
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "e-XpertSolutions/f5-rest-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月7日(星期二) 晚上11:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [e-XpertSolutions/f5-rest-client]  cannot commit transaction: Missing transaction ID for this call. (code: 404) (Issue #36)





 
Hello @asveg,
 
I just validated with our internal test suite and I did not encounter any issue with the transactions on the LTM part.
 
Can you provide me with some code snippet so that I can help you troubleshoot your code?
 
Given the information you provided so far, I think the problem is that you are not creating the objects within the transaction scope, that's why objects are created on the F5 and that's why the commit is not working, as there is no transaction ID. But it is hard to be 100% sure without your code.
 
You have an example that explains how to use transaction in the library in the documentation: https://pkg.go.dev/github.com/e-XpertSolutions/f5-rest-client/f5#Client.Begin
