### ISSUE TITLE
util BashCommand Run function broken

### ISSUE THREAD

**Issue by jneese** [e-XpertSolutions/f5-rest-client#42]
the bash resource run function makes a request, but incorrectly names the variable "resp", and never calls "br.c.Do(req)"
The object returned is basically the same bashcommand object that is put into the function.

**Comment by gilliek** [comment]
Thank you for reporting the problem.

There is indeed an issue. Bash command executions are available in the `f5.Client` object:

https://pkg.go.dev/github.com/e-XpertSolutions/f5-rest-client/f5#Client.Exec

We will fix the problem by making [util#BashResource.Run](https://pkg.go.dev/github.com/e-XpertSolutions/f5-rest-client@v1.0.1/f5/util#BashResource.Run) method an alias of [f5#Client.Exec](https://pkg.go.dev/github.com/e-XpertSolutions/f5-rest-client/f5#Client.Exec).

The main implementation is located in the `f5` package as we intend to make it more advanced in the future by supporting options, for instance, to execute over SSH instead of HTTP.
